Feature/master/wp 42 save authz code flow prefs
curityio/oauthtest pull request #43
Opened 2016-11-28 20:44 UTC by travisspencer

2016-11-28 21:12 UTC, renatoathaydes commented on oauthtest-core/src/main/java/se/curity/oauth/core/controller/SslSettingsController.java
> +                onCloseRequest.handle(e);
I think a better approach would be to set only one closeRequestHandler on the MainController that listens to all the relevant states it needs to save when we close the Stage.

2016-11-28 21:18 UTC, renatoathaydes requested changes
I would prefer to have only a single `onClose` handler on the Stage. This can be achieved by having listeners to all events that we want to save in preferences in just one place.

It would be easier to see what gets saved and we wouldn't need to repeat this code several times.

2016-12-03 09:05 UTC, travisspencer commented on oauthtest-core/src/main/java/se/curity/oauth/core/controller/SslSettingsController.java
> +                onCloseRequest.handle(e);
Fixed in 2dd4c2ce10bf6e3cb20eeb951d44e86fa8e62227

2016-12-03 18:57 UTC, renatoathaydes approved these changes

2016-12-03 18:58 UTC, merged